### ISSUE TITLE
Partials & Helpers support

### ISSUE THREAD

**Issue by nason** [segmentio/metalsmith-templates#3]
Consolidate.js supports partials for hogan, mustache, handlebars, and ractive. It also appears to support helpers for handlebars.

Does this plugin expose any of that functionality? Would be very nice :cookie:

**Comment by linclark** [comment]
For anyone coming to this issue, I created a small module that will register handlebars partials to the handlebars global, as suggested in https://github.com/segmentio/metalsmith-templates/issues/3#issuecomment-37147574.

https://www.npmjs.com/package/metalsmith-register-partials

**Comment by ianstormtaylor** [comment]
Sick! Thanks @linclark !

**Comment by jmatsushita** [comment]
For others looking into how to register handlebars helpers, this did it for me : https://github.com/linclark/metalsmith-register-partials
