### ISSUE TITLE
To tidy template modules

### ISSUE THREAD

**Issue by muchweb** [segmentio/metalsmith-templates#44]
There is `metalsmith-templates`, `metalsmith-in-place` and `metalsmith-layouts` that seem to do *very* similar things.

This could be well-confusing for the users.

Propose to __deprecate__ either this one or (`metalsmith-in-place` and `metalsmith-layouts`).

Related: https://github.com/segmentio/metalsmith-templates/issues/35

**Comment by ianstormtaylor** [comment]
Deprecated! Good call, thanks!
